# shelld test configuration with recycle mode

[server]
port = 8085
die_on_unlock = false

[shell]
command = "/bin/bash"

[timeout]
command = "30s"
command_maximum = "5m"
idle = "5m"
shutdown = "10s"
kill = "2s"

[hooks]
shell = "/bin/sh"
lock = ""
unlock = ""
